### ISSUE TITLE
improve unit-input 

### ISSUE THREAD

**Issue by 2youyou2** [cocos-creator-packages/ui-kit#91]
在 input 中输入小数 如下
![image](https://cloud.githubusercontent.com/assets/1862402/8745240/60ae38d6-2cb0-11e5-99b1-5a434c9fbbf1.png)
如果只是删除小数部分第二位小数，会自动将所有小数部分清除。
![image](https://cloud.githubusercontent.com/assets/1862402/8745269/9d68f96e-2cb0-11e5-8216-552050f8e6c0.png)

**Comment by w88975** [comment]
不影响使用,但用户体验不好
原因在于 parseFloat(1.0)会自动转换成 1, 这里涉及到一个Number和String类型的转换,所以再去toFixed精度可能会有问题,暂时先保留,
